# wjdlz/NOTE: @vx/ci
name: Release

on:
  schedule:
    - cron: '30 23 * * 2,5' # Wed, Sat at 5am IST
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: false
        description: version to publish
        default: ''
  release:
    types: [published]

run-name: "${{ github.event.inputs.version && format('ci(TVA): Release for {0}', github.event.inputs.version) || github.event_name == 'schedule' && 'ci(TVA): Release' || github.event_name == 'workflow_dispatch' && !github.event.inputs.version && 'ci(TVA): Dry Run - Release' || github.event.head_commit.message || github.event.workflow_run.head_commit.message || github.ref_name }} - by @${{ github.event_name == 'schedule' && 'vx' || github.actor || 'vx/ci' }}"

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  # cancel-in-progress: true
  # timeout-minutes: 10

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  REPO: ${{ github.repository }} # inputs.GIT_REPO
  BRANCH: ${{ github.ref_name }} # inputs.GIT_BRANCH
  NX_NO_CLOUD: true
  DX_KIT_NAME:

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: action | checkout | ${{ env.REPO }}@${{ env.BRANCH }}
        uses: vezham/vx-fe-deployer/.github/actions/common/setup-checkout@timeline
        with:
          GIT_REPO: ${{ env.REPO }}
          GIT_BRANCH: ${{ env.BRANCH }}

      - name: action | node & pnpm
        uses: vezham/vx-fe-deployer/.github/actions/common/setup-install-npm@timeline
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: fork | build
        # id: build
        continue-on-error: false
        shell: bash
        run: |
          pnpm @vx/ci/build || {
            echo "build failed with exit code $?"
            exit 1
          }

      - name: action | nx/NPM-release
        uses: vezham/vx-fe-deployer/.github/actions/nx/release@timeline
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PROVENANCE: false
          version: ${{ github.event.inputs.version }}

      - name: action | nx/AI fix
        if: always()
        uses: vezham/vx-fe-deployer/.github/actions/nx/ai-fix@timeline
